version: "3"
services:
  web:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/opt/app
    ports:
      - "3000:3000"
    links:
      - mongo
    entrypoint:
      - yarn
      - run
      - "start:dev"
  
  mongo:
    image: mongo:3.4.9
    ports:
      - "27017:27017"
    volumes:
      - "~/data/db:/data/db"
